<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Code</title>

    <style>
        #load_date {
            color: green;
        }

        .code_block {
            width: 50%;
            border-style: solid;
            border-width: 1px;
            background: lightgray;

        }
    </style>
</head>
<body>

<code><span id="load_date">${code.}</span></code>
<div class="code_block">
    <pre id="code_snippet"><code>{code_snippet}</code></pre>
</div>

</body>
</html>